<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAnAVTAK\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAnAVTAK/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAnAVTAK.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAnAVTAK\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAnAVTAK\App_KernelProdContainer([
    'container.build_hash' => 'AnAVTAK',
    'container.build_id' => '71fecc4c',
    'container.build_time' => 1643033136,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAnAVTAK');
