<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'signup_administrateur' => [[], ['_controller' => 'App\\Controller\\AdministrateurBackofficeController::signup_administrateur'], [], [['text', '/login/']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\AdministrateurBackofficeController::logout'], [], [['text', '/logout']], [], [], []],
    'add_administrateur' => [[], ['_controller' => 'App\\Controller\\AdministrateurBackofficeController::add_administrateur'], [], [['text', '/admin/administrateur/create']], [], [], []],
    'delete_administrateur' => [[], ['_controller' => 'App\\Controller\\AdministrateurBackofficeController::delete_administrateur'], [], [['text', '/admin/administrateur/delete']], [], [], []],
    'delete_id_administrateur' => [['id'], ['_controller' => 'App\\Controller\\AdministrateurBackofficeController::delete_id_administrateur'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/administrateur/delete']], [], [], []],
    'backoffice_contact' => [[], ['_controller' => 'App\\Controller\\ContactBackofficeController::index'], [], [['text', '/admin/contact']], [], [], []],
    'delete_id_contact' => [['id'], ['_controller' => 'App\\Controller\\ContactBackofficeController::delete_id_administrateur'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/contact/delete']], [], [], []],
    'add_exposition' => [[], ['_controller' => 'App\\Controller\\ExpositionController::create_exposition'], [], [['text', '/admin/expoxition/create']], [], [], []],
    'manage_exposition' => [[], ['_controller' => 'App\\Controller\\ExpositionController::delete_id_administrateur'], [], [['text', '/admin/exposition/manage']], [], [], []],
    'delete_id_exposition' => [['id'], ['_controller' => 'App\\Controller\\ExpositionController::delete_id_exposition'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/exposition/delete']], [], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\RealisationBackofficeController::dashboard'], [], [['text', '/admin/dashboard']], [], [], []],
    'add_oeuvre' => [[], ['_controller' => 'App\\Controller\\RealisationBackofficeController::add_artwork'], [], [['text', '/admin/oeuvre/create']], [], [], []],
    'update_oeuvre' => [['id'], ['_controller' => 'App\\Controller\\RealisationBackofficeController::update_artwork'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/oeuvre/update']], [], [], []],
    'manage_oeuvre' => [[], ['_controller' => 'App\\Controller\\RealisationBackofficeController::manage_artwork'], [], [['text', '/admin/oeuvre/manage']], [], [], []],
    'delete_id_artwork' => [['id'], ['_controller' => 'App\\Controller\\RealisationBackofficeController::delete_id_administrateur'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/oeuvre/delete']], [], [], []],
    'about' => [[], ['_controller' => 'App\\Controller\\VitrineWebsiteController::index'], [], [['text', '/']], [], [], []],
    'galerie' => [[], ['_controller' => 'App\\Controller\\VitrineWebsiteController::galerie'], [], [['text', '/galerie']], [], [], []],
    'expositions' => [[], ['_controller' => 'App\\Controller\\VitrineWebsiteController::expositions'], [], [['text', '/expositions']], [], [], []],
    'galerie_oeuvre' => [['id'], ['_controller' => 'App\\Controller\\VitrineWebsiteController::galerie_oeuvre'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/galerie-oeuvre']], [], [], []],
    'mentions_legales' => [[], ['_controller' => 'App\\Controller\\VitrineWebsiteController::mention'], [], [['text', '/mentions-legales']], [], [], []],
    'politiques_confidentialites' => [[], ['_controller' => 'App\\Controller\\VitrineWebsiteController::politique'], [], [['text', '/politiques-confidentialites']], [], [], []],
    'page_404' => [[], ['_controller' => 'App\\Controller\\VitrineWebsiteController::lost_page'], [], [['text', '/perdu-sur-mon-site']], [], [], []],
    'backoffice_websiteSave' => [[], ['_controller' => 'App\\Controller\\WebSiteSaveBackofficeController::index'], [], [['text', '/admin/web-site']], [], [], []],
];
