<?php

namespace ContainerXaAnUDC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JwmFYI4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JwmFYI4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JwmFYI4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'administratorRepository' => ['privates', 'App\\Repository\\AdministratorRepository', 'getAdministratorRepositoryService', true],
        ], [
            'administratorRepository' => 'App\\Repository\\AdministratorRepository',
        ]);
    }
}
