<?php

namespace ContainerAnAVTAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LuPO1afService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.LuPO1af' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LuPO1af'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'administratorRepository' => ['privates', 'App\\Repository\\AdministratorRepository', 'getAdministratorRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'administratorRepository' => 'App\\Repository\\AdministratorRepository',
            'em' => '?',
        ]);
    }
}
