<?php

namespace ContainerAnAVTAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpositionRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ExpositionRepository' shared autowired service.
     *
     * @return \App\Repository\ExpositionRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ExpositionRepository'] = new \App\Repository\ExpositionRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
