<?php

namespace ContainerAnAVTAK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVitrineWebsiteControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\VitrineWebsiteController' shared autowired service.
     *
     * @return \App\Controller\VitrineWebsiteController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\VitrineWebsiteController'] = $instance = new \App\Controller\VitrineWebsiteController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\VitrineWebsiteController', $container));

        return $instance;
    }
}
