<?php

namespace ContainerZMxReHM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AmlsGwrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.amlsGwr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.amlsGwr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'artworkRepository' => ['privates', 'App\\Repository\\ArtworkRepository', 'getArtworkRepositoryService', true],
        ], [
            'artworkRepository' => 'App\\Repository\\ArtworkRepository',
        ]);
    }
}
