<?php

namespace ContainerZMxReHM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G5GwKLkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.g5GwKLk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.g5GwKLk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'expositionRepository' => ['privates', 'App\\Repository\\ExpositionRepository', 'getExpositionRepositoryService', true],
        ], [
            'em' => '?',
            'expositionRepository' => 'App\\Repository\\ExpositionRepository',
        ]);
    }
}
