<?php

namespace ContainerZMxReHM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J8Hw6yOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J8Hw6yO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J8Hw6yO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'artworkRepository' => ['privates', 'App\\Repository\\ArtworkRepository', 'getArtworkRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'artworkRepository' => 'App\\Repository\\ArtworkRepository',
            'em' => '?',
        ]);
    }
}
