<?php

namespace ContainerZMxReHM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JlulvMvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jlulvMv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jlulvMv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'websiteSaveRepository' => ['privates', 'App\\Repository\\WebsiteSaveRepository', 'getWebsiteSaveRepositoryService', true],
        ], [
            'websiteSaveRepository' => 'App\\Repository\\WebsiteSaveRepository',
        ]);
    }
}
