<?php

namespace ContainerZMxReHM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DCHypUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dCHyp_u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dCHyp_u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'factory' => ['privates', 'form.factory', 'getForm_FactoryService', true],
        ], [
            'doctrine' => '?',
            'factory' => '?',
        ]);
    }
}
